### ISSUE TITLE
Two leftover acid tubes inside old alien default.

### ISSUE THREAD

**Issue by mjstahlberg** [UnvanquishedAssets/map-parpax_src.dpkdir#1]
There are two acid tubes in the old alien base location ("strange machine" room on the upper level). In `0.50.0` they die on map start since there is no creep. In 0.51.0 they would live, and could be farmed by the human team for momentum gain.

**Comment by illwieckz** [comment]
If I remember correctly, you were also suspecting that some buildables could also be stuck in solid, that was supposed to be a cause for the now-fixed “_game crash on current master with parpax map_” issue (Unvanquished/Unvanquished#995).

**Comment by mjstahlberg** [comment]
I'll check that, too. Currently updates to parpax are blocked by [a netradiant issue](https://gitlab.com/xonotic/netradiant/issues/112), though.

**Comment by illwieckz** [comment]
@Viech said it was fixed.
