### ISSUE TITLE
Bots don't know they can pass through the elevator when it is at the right position

### ISSUE THREAD

**Issue by necessarily-equal** [UnvanquishedAssets/map-parpax_src.dpkdir#11]
That means that someone standing in the elevator will never be attacked, both when the elevator is in the upper and in the lower position.

"the elevator is lava", bots said.

**Comment by mjstahlberg** [comment]
This is nothing that can be fixed on map level and I don't think there is a reasonable workaround. Closing as also that particular elevator was removed in the last update.
