### ISSUE TITLE
weird hint brush geometry

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/map-parpax_src.dpkdir#5]
are those hint brushes expected to have any effect?

[![parpax](https://dl.illwieckz.net/b/unvanquished/bugs/maps/parpax/hint/20181006-055741-000.unvanquished-netradiant-parpax.png)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/parpax/hint/20181006-055741-000.unvanquished-netradiant-parpax.png)

[![parpax](https://dl.illwieckz.net/b/unvanquished/bugs/maps/parpax/hint/20181006-145837-000.unvanquished-netradiant-parpax.png)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/parpax/hint/20181006-145837-000.unvanquished-netradiant-parpax.png)

[![parpax](https://dl.illwieckz.net/b/unvanquished/bugs/maps/parpax/hint/20181006-145928-000.unvanquished-netradiant-parpax.png)](https://dl.illwieckz.net/b/unvanquished/bugs/maps/parpax/hint/20181006-145928-000.unvanquished-netradiant-parpax.png)

**Comment by mjstahlberg** [comment]
Nope, they would need to touch structural brushwork. The doorways were probably extended after the hint was placed.
